# Generated by Django 3.2.7 on 2023-10-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
    ]
